name: 'Call Dagger Function'
description: 'Calls a Dagger pipeline function'
inputs:
  task:
    description: 'The task to run'
    required: true
    default: 'test'
runs:
  using: 'composite'
  steps:
    - name: Go Setup
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.4
        cache: false

    - name: Run Pipeline
      uses: dagger/dagger-for-github@v6
      with:
        version: "0.15.1"
        workdir: .
        verb: call
        args: --source=. ${{ inputs.task }}