name: Dagger Pipeline
on:
  push:
    branches:
      - main

    pull_request:
      types: [ opened, synchronize, reopened ]
      branches:
        - main
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [format, lint, test, coverage]
    steps:
      - uses: actions/checkout@v4
      - name: Run Dagger ${{ matrix.task }}
        uses: ./.github/actions/function-call
        with:
          task: ${{ matrix.task }}
