name: Dagger Pipeline
on:
  push:
    branches:
      - main

    pull_request:
      types: [ opened, synchronize, reopened ]
      branches:
        - main
    workflow_dispatch:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dagger Format
        uses: ./.github/actions/function-call
        with:
          task: format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dagger Lint
        uses: ./.github/actions/function-call
        with:
          task: lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dagger Test
        uses: ./.github/actions/function-call
        with:
          task: test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Dagger Coverage
        uses: ./.github/actions/function-call
        with:
          task: coverage
