name: Rust
on:
  push:
    branches:
      - main

    pull_request:
      types: [ opened, synchronize, reopened ]
      branches:
        - main
    workflow_dispatch:

jobs:
  dagger:
    name: Dagger Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache: false

      - name: Run Pipeline
        uses: dagger/dagger-for-github@v6
        with:
          workdir: .
          verb: run
          args: go run dagger/main.go
          version: "0.15.1"
